### ISSUE TITLE
tests fail due to updated mutagen version

### ISSUE THREAD

**Issue by jrobeson** [beetbox/mediafile#2]
See this https://github.com/beetbox/beets/pull/2088 and potentially other changes to mediafile https://github.com/beetbox/beets/commits/master/beets/mediafile.py

**Comment by jackwilsdon** [comment]
I'm considering nuking the history here (i.e. force pushing) and rebasing the changes made in [beetbox/beets](https://github.com/beetbox/beets) onto here.

It's how I created the history in the first place and it shouldn't hurt to do it again? I know force pushing is bad but it seems the best way really, as this is kind of still "up in the air" at the moment.

**Comment by jrobeson** [comment]
I think at least one more force push should be done, but can we save it until we split from beets? You folks said that 1.4.0 would be the release in which we'd split beets, and that's the next one.  Can we split now?

**Comment by jrobeson** [comment]
Oh, and if we do, then it's time to stop allowing 3.x failures on travis (and maybe appveyor too)

**Comment by jackwilsdon** [comment]
@jrobeson: Well the force push would be needed to actually split from beets, as it would bring us up to date with the version of `mediafile.py` that is currently in beets.

I'll sort out the tests being ignored too.

**Comment by jrobeson** [comment]
I thought that's what i said? what led to the impression i meant otherwise? wanna pop in irc?

**Comment by jackwilsdon** [comment]
Ah, I understood this part of what you said:

> but can we save it until we split from beets

As meaning "only do it after splitting from beets" 😆. I can't join IRC right now sadly but I should be on soon (possibly tomorrow).

**Comment by jrobeson** [comment]
I understand now, sorry for the confusion.  I meant that as in "right before we split"

**Comment by sampsyo** [comment]
Yes! I fully endorse force-pushing to this repo while the split is still in flux.

**Comment by sampsyo** [comment]
I've done a bit more work to bring things up to speed, and this bug has gone away.

Currently, the `mediafile.py` here and in the beets repository match exactly (except for the copyright line). So if anyone's interested in preserving the ancient MF history, it would be safe to replace all the history here with that history—in other words, it's safe to transition now.
