### ISSUE TITLE
Add barcode as mediafield

### ISSUE THREAD

**Issue by SimonHova** [beetbox/mediafile#26]
I use mediafile to update my music as an alternative Python-based [ampache](https://github.com/ampache/ampache) scanner, and it works wonderfully; however the one field that ampache needs is the barcode field, and I have to make an expensive call back to MusicBrainz to fetch it. Can someone please add the barcode field to the list of fields that it can retrieve?

**Comment by sampsyo** [comment]
Please feel free to open a pull request! It's not terribly hard to introduce a new tag mapping; you mostly have to copy n' paste an existing one and change the tag names.

**Comment by SimonHova** [comment]
Okay! I'll give it a go, and post the update here. Thanks!

**Comment by sampsyo** [comment]
Added in https://github.com/beetbox/mediafile/pull/27.
