### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by adamjakab** [beetbox/mediafile#31]
https://github.com/beetbox/mediafile/blob/8846cdf226ee61ec181b03f0133046bc37cebd3d/mediafile.py#L1611

should read: ... "already exists on MediaFile" not `MediaField`.

**Comment by sampsyo** [comment]
Thanks!! Would you like to do the honors of opening a pull request so you get the credit? :smiley:

**Comment by JuniorJPDJ** [comment]
@adamjakab have you fixed it and done pull request? I'm not sure why that easy issue is still open :D

**Comment by adamjakab** [comment]
Hey @JuniorJPDJ - thanks for the note. At the moment I have no bandwidth to do this. Would you be able to do it?

**Comment by sampsyo** [comment]
I changed it! It's a little confusing, but here `cls` is `MediaFile` itself, while `descriptor` is a `MediaField` instance—and the error is trying to say "this `MediaField` already exists on `MediaFile`".
