### ISSUE TITLE
Support filelike objects, not only pathes

### ISSUE THREAD

**Issue by JuniorJPDJ** [beetbox/mediafile#35]
Hi!
I'm trying to use this library with remote files defined as file-likes in python.
`mutagen` supports file-like interface, why tho mediafile doesn't?
Docs say it needs local file path as first argument.

**Comment by sampsyo** [comment]
Sounds like a reasonable addition! A PR would be welcome.

**Comment by JuniorJPDJ** [comment]
It works, would just need rename of path to filelike

**Comment by sampsyo** [comment]
OK! Updates to the naming and the docs would still be welcome in a PR. (But we wouldn't want to call it `filelike` because it can also be a path. :smiley:)

**Comment by JuniorJPDJ** [comment]
Nvm, saving doesn't work if using filelike.

**Comment by sampsyo** [comment]
Sure! That seems worth a shot. Thanks for looking into it!
