### ISSUE TITLE
Empty fields returning None

### ISSUE THREAD

**Issue by jtpavlock** [beetbox/mediafile#38]
Going off [the docs](https://mediafile.readthedocs.io/en/latest/).

> MediaFile attempts to always return a usable value (i.e., it never returns None or throws an exception when a tag is accessed). If a tag is not present, an empty and false value of the appropriate type – such as zero or the empty string – is returned.

```python
>>> f = MediaFile('tests/resources/audio_files/empty.mp3')
>>> print(f.title)
None
```

Is this going against expected behavior or maybe the docs are out of date?

**Comment by sampsyo** [comment]
That's a good point—this did change in https://github.com/beetbox/beets/pull/660, and it also looks like the docstring for `_safe_cast` is out of date. Fields can now return None _if the tag is missing altogether_, which is useful for some clients.
