### ISSUE TITLE
Crash on import of library.

### ISSUE THREAD

**Issue by dbuttric** [beetbox/mediafile#53]
I started the import run for the first time, and it got about ten albums in, and this happened.
The import will not proceed past this problem.

[beet crash.txt](https://github.com/beetbox/mediafile/files/7232000/beet.crash.txt)
.
Please let me know what other information I need to provide here to assist you.

**Comment by JuniorJPDJ** [comment]
Python 3.6 doesn't have keyword argument for start:

https://docs.python.org/3.6/library/functions.html?highlight=sum#sum

I'll do pull request
