### ISSUE TITLE
Add github releases to tags

### ISSUE THREAD

**Issue by JuniorJPDJ** [beetbox/mediafile#55]
Main issue with only tagging is v0.1.0 showing as latest version in releases section of sidebar.
![Screenshot_20210926_210651](https://user-images.githubusercontent.com/7334549/134820917-42d70546-656a-4346-b41c-5e5289ed267c.png)

**Comment by sampsyo** [comment]
Done; thanks for the hint! I've turned all our version tags into releases.

Kinda makes me wish this just happened automatically? Maybe some Action like [this](https://github.com/marketplace/actions/github-create-tag-release) could help…

**Comment by JuniorJPDJ** [comment]
I personally never played with actions for this so I ain't help much, but it seems like a good idea!
