### ISSUE TITLE
`imghdr` is deprecated and slated for removal in Python 3.13

### ISSUE THREAD

**Issue by labrys** [beetbox/mediafile#67]
The Python standard library will be removing [`imghdr`](https://docs.python.org/3/library/imghdr.html) in Python 3.13.  Per [PEP-594](https://peps.python.org/pep-0594/#deprecation-schedule) suggested replacements are [filetype](https://pypi.org/project/filetype/), [puremagic](https://pypi.org/project/puremagic/), and [python-magic](https://pypi.org/project/python-magic/).

**Comment by sampsyo** [comment]
Yes indeed—thanks for opening the issue. We should switch sooner rather than later.

(It's too bad about these deprecations, to be honest! I know they were rarely used, but they did their job quietly and well…)

**Comment by baldurmen** [comment]
Python 3.13 will be released shortly and that's what we'll be using for the next Debian release (Debian 13).

If this issue isn't fixed before we freeze packages for Debian 13 (sometime in Q1 2025?), we won't be able to ship this library and that'll snowball to other distros like Ubuntu and Linux Mint :(

**Comment by gbcox** [comment]
It has been patched in Fedora F41.  Just has to be propagated through the mirrors:
* Sat Nov 02 2024 Michele Baldessari <michele@acksyn.org> - 0.12.0-6
- Apply patches from v0.12.0 to 6accdc4c4a7fe4d808b674a97fb5474e12621504
- Also apply PR 73 to avoid python 3.13 breakage (although it will regress on more obscure image formats)

**Comment by jackwilsdon** [comment]
mediafile v0.13.0 has been released with this fix.
