### ISSUE TITLE
six usage is redundant

### ISSUE THREAD

**Issue by pgajdos** [beetbox/mediafile#68]
Could you please eventually consider to drop dependency on six as long as you declare only python 3 support?

**Comment by sampsyo** [comment]
Yes indeed; any help removing the dependency would be appreciated!

**Comment by pgajdos** [comment]
It seems pyupgrade do the job

https://build.opensuse.org/package/view_file/home:pgajdos:python/python-mediafile/python-mediafile-pyupgrade.patch?expand=1
