### ISSUE TITLE
Version bump to down integrate to beets

### ISSUE THREAD

**Issue by chrisbenincasa** [beetbox/mediafile#76]
Hello, I'm just wondering what the release process is for this repo. A few months ago I authored 93c6c3bc7541ad169824ac603267e9c02fe4ecd5 which unfortunately still hasn't been tied to an official release of this library, from what I can tell. Im hoping that we could get a release here so that I could potentially bump the version in beets and take advantage of the commit. Thanks!

**Comment by jackwilsdon** [comment]
Apologies for the delay - v0.13.0 has been released :tada:
